/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.jeffreypratt.mxcpu;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Arrays;

public class App {
    public static void main(String[] args) {
        if (args.length < 1) {
            System.out.println("File required.");
            System.exit(1);
        }

        try {
            int[] program = loadProgram(Paths.get(args[0]));

            Cpu cpu = new Cpu(new CpuState());
            cpu.run(program);

            System.out.println(cpu.getState());
        } catch (IOException | UnknownOpCodeException | LongRunTimeException e) {
            System.out.println(e.getMessage());
            System.exit(1);
        }
    }

    private static int[] loadProgram(Path path) throws IOException {
        byte[] bytes = Files.readAllBytes(path);
        String contents = new String(bytes).trim();

        return Arrays.stream(contents.split(" "))
                .mapToInt(s -> Integer.parseInt(s, 16))
                .toArray();
    }
}
